### ISSUE TITLE
Run on exomes?

### ISSUE THREAD

**Issue by seandavi** [walaj/snowman#1]
Hi, @walaj. This looks like something that I would like to try out.  We have a project with about 50/50 mix of genomes and exomes.  I understand that the exome SV/indel calls will be limited, but is there any particular reason that snowman could not be applied to exomes?

**Comment by walaj** [comment]
Hi Sean, yes this will work well on exomes. As you say, you're unlikely to find many large SVs in the exomes, but if one of the two breakpoints is in or very near a capture region it should pick it up, which I have occasionally seen. Otherwise there is no fundamental problem with running on exomes-only, and snowman works well for indels. Would be interested to hear how this works for you if you end up deciding to try, hopefully it should be easy to setup and run!
